[book]
authors = ["Marlon Baeten"]
language = "en"
multilingual = false
src = "src"
title = "Rust TSP Guides"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]