[book]
authors = ["Marlon Baeten"]
language = "en"
multilingual = false
src = "src"
title = "Rust TSP Guides"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/openwallet-foundation-labs/tsp/tree/main/docs"
hash-files = true
cname = "docs.teaspoon.world"